services:
    guzzle.client:
        class: GuzzleHttp\Client
        arguments: [{base_uri: '', headers: {'user-agent': 'guzzle'}}]
        public: false

    cloudinary_storage_service:
        class: Victor\FileStorageBundle\Cloudinary\Cloudinary
        arguments:
            - 'one'
            - 'two'
            - 'three'
            - 'four'
            - 'five'
            - 'client'
        tags:
            - { name: file_storage, alias: routing_widget }

    cloudinary.cloudinary_form_extension:
        class: Victor\FileStorageBundle\Form\CloudinaryFileExtension
        arguments:
            - "@cloudinary_storage_service"
        tags:
            - { name: form.type_extension, alias: cloudinary_file_type, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
