services:
    guzzle.client:
        class: GuzzleHttp\Client
        arguments: [{base_uri: '', headers: {'user-agent': 'guzzle'}}]
        public: false

    cloudinary_storage_config:
        class: Victor\FileStorageBundle\Cloudinary\Config

    cloudinary_storage_service:
        class: Victor\FileStorageBundle\Cloudinary\Cloudinary
        arguments:
            - '@cloudinary_storage_config'
            - '@guzzle.client'
        tags:
            - { name: file_storage, alias: cloudinary_storage_service }

    cloudinary.cloudinary_form_extension:
        class: Victor\FileStorageBundle\Form\CloudinaryFileExtension
        arguments:
            - "@cloudinary_storage_service"
            - "@cloudinary.uri_generator"
        tags:
            - { name: form.type_extension, alias: cloudinary_file_type, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

    cloudinary.uri_generator:
        class: Victor\FileStorageBundle\Cloudinary\Transformation\UriGenerator

    cloudinary.scale_generator:
        class: Victor\FileStorageBundle\Cloudinary\Transformation\ScaleGenerator
        tags:
            - { name: cloudinary.transformation_generator }