services:
    guzzle.client:
        class: GuzzleHttp\Client
        arguments: [{base_uri: '', headers: {'user-agent': 'guzzle'}}]
        public: false

    cloudinary_storage_service:
        class: Victor\FileStorageBundle\Cloudinary\Cloudinary
        arguments:
            - 'one'
            - 'two'
            - 'three'
            - 'four'
            - 'five'
            - 'client'
        tags:
            - { name: file_storage, alias: routing_widget }
